### ISSUE TITLE
Should OpenWhisk web actions that return an error HTTP status code be treated as errors?

### ISSUE THREAD

**Issue by trieloff** [epsagon/epsagon-node#124]
I'm unsure if this is a bug, or what the desired behavior should be:

I have a function that will return a HTTP status code 404 if it can't find a particular file, e.g. by calling `https://adobeioruntime.net/api/v1/web/helix/helix-services/static@ci109?owner=trieloff&repo=helix-demo&ref=master&entry=/index.js&plain=true` and it returns 200 when everything is ok: `http "https://adobeioruntime.net/api/v1/web/helix/helix-services/static@ci109?owner=trieloff&repo=helix-demo&ref=master&entry=/index.js&plain=true&root=/htdocs"`

Both kinds of behavior are expected by the action developer, but not necessarily by the user of the action. 

For HTTP requests made by the function, Epsagon treats everything >=400 as an error. Should the same rule apply to HTTP responses returned by the action? 

I could also see that only HTTP status codes >=500 should be treated as an error in the action, and 4xx status code indicate an error only from the perspective of the caller, i.e. if it's called externally, then it's not an error, but if observed through #122 then it should be reported as an error, similar to a failed HTTP request.

**Comment by ranrib** [comment]
Hi, In general you are right for this case - but since we will do soon https://github.com/epsagon/epsagon-node/issues/122, I think this one will be irrelevant. right?

**Comment by trieloff** [comment]
No, this and #122 are largely orthogonal. #122 treats the observation of outgoing invocations, and what I'm wondering is how to deal with execution failures that got handled correctly, but are still failures.

**Comment by ranrib** [comment]
Well, it's really depends.
I guess there's no doubt that >=500 should be treated as errors.
For 400 ones - as it indicates a client side error, IMO, since you're at the side that making the call - you want to be notified. Think as if this call was to some 3rd party that you don't own - you would definitely want to know about it.

But as I mentioned, since we are going to implement a specific instrumentation for wsk, we can ignore anything that is not >=500 - so in this specific case it helps you.

Do you think otherwise? We will be able to probably set the 400/500 as a configuration if you think that other developers might want a different behaviour.

**Comment by trieloff** [comment]
In my app, `404` is exceedingly common (not just because we are serving stuff to web browsers, but also because we do speculative requests in parallel). `403/401` would be something to look out for. 

It's probably a good idea to add a switch, so you can fine-tune the selectiveness.
