### ISSUE TITLE
serverless-plugin-epsagon leads to Internal Server error

### ISSUE THREAD

**Issue by Strernd** [epsagon/epsagon-node#8]
When I use the serverless-plugin-epsagon with my lambda function, it stops working.

Reproduction:

- Create basic function template with serverless framework
- Add HTTP handler
- install epsagon and plugin
- Supply token to epsagon config in serverless.yml
- Deploy function

Call HTTP: 
{"message": "Internal server error"}

- Comment out the epsagon plugin
- Deploy function

Call HTTP:
{ "message": "Hello World!" }

**Comment by galbash** [comment]
Hi @Strernd  thanks for taking the time to open an issue! We will get right on it and fix it :) In the meantime, can you please help me verify that the error is what I think it is?
I think it is a bug introduced in the latest version, where pg should be an optional dependency but if not there epsagon won't load. We will fix it ASAP, but just to make sure you don't experience a different issue - can you check the CW logs of your function and verify that the issue is similar to "Cannot find module 'pg'"?

Thanks!

@ilyaLibin  - please have a look

**Comment by ranrib** [comment]
Relevant PR: https://github.com/epsagon/epsagon-node/pull/9

**Comment by ilyaLibin** [comment]
@Strernd Thanks again for the report. I have published a new version, that should fix the issue. Please make sure the `v1.1.1` of epsagon npm package installed.

**Comment by ilyaLibin** [comment]
Relevant PR: https://github.com/epsagon/epsagon-node/pull/9

**Comment by Strernd** [comment]
Can confirm it works now. Thanks.
